<div class="row">
	<div class="col-sm-8">
	  <h1>Bootstrap starter template</h1>
	  <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>

		<a class="btn btn-primary" href="pages/ajax.phtml"><i class='glyphicon glyphicon-ok'></i> Load next page</a>
	</div>
	<div class="col-sm-4" data-load="pages/sidebar.phtml">
	</div>
</div>

<div class="row">
	</div>
</div>